openapi: 3.0.1
info:
  title: Mongo model test
  description: Mongo model test
  version: 1.0.0
servers:
- url: localhost:27017
paths:
  /ping:
    get:
      responses:
        200:
          description: OK
          content: {}
components:
  schemas:
    Category:
      type: object
      x-mongo-collection-name: categories
      properties:
        id:
          type: integer
          format: int64
          x-mongo-index: true
        name:
          type: string
          x-mongo-index: true
          x-mongo-ordered-index: true

    Tag:
      type: object
      x-mongo-collection-name: tags
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: Tag
    Pet:
      required:
      - name
      - photoUrls
      type: object
      x-mongo-collection-name: pets
      properties:
        id:
          type: integer
          format: int64
        category:
          $ref: '#/components/schemas/Category'
        name:
          type: string
          example: doggie
        photoUrls:
          type: array
          xml:
            name: photoUrl
            wrapped: true
          items:
            type: string
        tags:
          type: array
          xml:
            name: tag
            wrapped: true
          items:
            $ref: '#/components/schemas/Tag'
        status:
          type: string
          description: pet status in the store
          enum:
          - available
          - pending
          - sold